evidence(topic(p1,sport),true).
evidence(topic(p1,food),false).
evidence(topic(p1,politics),false).
evidence(topic(p2,sport),true).
evidence(topic(p2,food),false).
evidence(topic(p2,politics),false).
evidence(topic(p3,politics),true).
evidence(topic(p3,food),false).
evidence(topic(p3,sport),false).
evidence(topic(p4,food),true).
evidence(topic(p4,sport),false).
evidence(topic(p4,politics),false).
evidence(topic(p5,politics),true).
evidence(topic(p5,food),false).
evidence(topic(p5,sport),false).
evidence(topic(p6,food),true).
evidence(topic(p6,sport),false).
evidence(topic(p6,politics),false).
evidence(topic(p7,sport),true).
evidence(topic(p7,food),false).
evidence(topic(p7,politics),false).