hyperlink(p1,p2).
hyperlink(p1,p3).
hyperlink(p1,p7).
hyperlink(p2,p7).
hyperlink(p3,p5).
hyperlink(p4,p6).
hyperlink(p5,p1).
hyperlink(p5,p7).
hasword(p1,soccer).
hasword(p1,goal).
hasword(p2,england).
hasword(p2,defeat).
hasword(p2,colombia).
hasword(p2,soccer).
hasword(p2,goal).
hasword(p3,guardian).
hasword(p3,elections).
hasword(p4,coffee).
hasword(p4,colombia).
hasword(p5,elections).
hasword(p5,president).
hasword(p5,england).
hasword(p5,game).
hasword(p6,restaurant).
hasword(p6,pasta).
hasword(p7,game).
hasword(p7,england).

%% 
t(_,T,W)::topic(P,T):-hasword(P,W).
%%t(_,W,T)::topic(T,P):-hasword(W,P).